### ISSUE TITLE
update to the control

### ISSUE THREAD

**Issue by zishanj** [danmarsden/moodle-profilefield_radio#1]
I wonder why this field is not included with Moodle core. This version works partially but it shows this error on user profile: 

> Element 'profile_field_gender' does not exist in HTML_QuickForm::addRule()

I am using gender field as a radio to test it. Although there is `addRule` defined in the `edit_field_add()` method but its still throwing this error.

**Comment by zishanj** [comment]
I have resolved this and some other compatibility issues.

**Comment by danmarsden** [comment]
cool - I don't even remember writing this plugin... when I saw this notification come through I though - what's the profilefield_radio plugin? - great you found it useful! :-)
